name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      run: |
         wget https://apt.devkitpro.org/install-devkitpro-pacman 
         chmod +x ./install-devkitpro-pacman
         sudo ./install-devkitpro-pacman
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
         cd templates/application/
         make -j$(nproc)
    - name: upload
      uses: actions/upload-artifact@v4
      with: 
        path: |
          .
