name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create Directory
      run: |
         mkdir \grr\GRRLIB\lib\pngu
         mkdir \grr\GRRLIB\GRRLIB
    - name: Install grrlib
      run: |
        sudo (dkp-)pacman --sync --needed --noconfirm libfat-ogc ppc-libpng ppc-freetype ppc-libjpeg-turbo
    - name: Compile
      run: |
         cd templates/application/
         make -j$(nproc)
    - name: upload
      uses: actions/upload-artifact@v4
      with: 
        path: |
          .
