name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
         make -f Makefile wii-examples/templates/application/ -j$(nproc)
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: wii
        path: |
          example.dol

