name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: Compile
      run: |
        make wii -j$(nproc)
        mv icon/icon-wiiu.png icon.png
        mv icon/meta.xml meta.xml
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: wii
        path: |
          icon.png
          meta.xml
          example.dol

