name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download and extract library for grrlib
      run: |
        wget -O library.tar.gz https://github.com/GRRLIB/GRRLIB/archive/refs/tags/v4.5.1.tar.gz
        mkdir library
        tar -xf library.tar.gz -C library --strip-components=1
    - name: Setup and use library
      run: |
        wget -O library.tar.gz https://github.com/GRRLIB/GRRLIB/archive/refs/tags/v4.5.1.tar.gz
        cd library
    - name: Compile
      run: |
         cd templates/application/
         make -j$(nproc)
    - name: upload
      uses: actions/upload-artifact@v4
      with: 
        path: |
          .
